# Generated by Django 6.1.1 on 2026-09-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=6)),
                ('app_label', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('object_pk', models.CharField(blank=True, default='', max_length=64)),
                ('changed_fields', models.JSONField(blank=True, default=list, help_text='Field NAMES only. Never values — that is what keeps PII out of this table.')),
                ('request_method', models.CharField(blank=True, default='', max_length=8)),
                ('request_path', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log',
                'ordering': ('-at', '-id'),
                'indexes': [models.Index(fields=['app_label', 'model_name', 'object_pk'], name='core_auditl_app_lab_073a56_idx')],
            },
        ),
        migrations.CreateModel(
            name='DatasetSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('dataset_kind', models.CharField(choices=[('SAMPLE', 'Sample data — not actuals'), ('ACTUAL', 'Actual data')], default='SAMPLE', help_text='While SAMPLE, every page renders the SAMPLE DATA — NOT ACTUALS banner.', max_length=6)),
                ('seed_journal_entry_ref', models.CharField(blank=True, default='', help_text='source_ref of the single balanced seed JE, e.g. SAMPLE_SEED_2026-09-20. Set by Slice B when the seed is loaded; cleared when it is reversed.', max_length=64)),
                ('flipped_to_actual_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'dataset settings',
                'verbose_name_plural': 'dataset settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='core_datasetsettings_singleton')],
            },
        ),
    ]
