# Generated by Django 6.1.1 on 2026-09-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dataset_settings_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='actor_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
