# Generated by Django 6.1.1 on 2026-09-25 06:12

import django.db.models.deletion
from django.db import migrations, models


CONTROLS_SQL = """
REVOKE UPDATE, DELETE ON acct_journalentry, acct_journalline
FROM PUBLIC, ops_writer, acct_writer;
REVOKE UPDATE, DELETE ON acct_acctmanualentry
FROM PUBLIC, ops_writer, acct_writer;

CREATE FUNCTION acct_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '% is append-only; post a reversal', TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER acct_journalentry_append_only BEFORE UPDATE OR DELETE ON acct_journalentry
FOR EACH ROW EXECUTE FUNCTION acct_append_only();
CREATE TRIGGER acct_journalline_append_only BEFORE UPDATE OR DELETE ON acct_journalline
FOR EACH ROW EXECUTE FUNCTION acct_append_only();

CREATE FUNCTION acct_manual_status_only() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'acct_acctmanualentry is append-only';
    END IF;
    IF (to_jsonb(NEW) - 'posted_entry_id' - 'posting_error')
       IS DISTINCT FROM (to_jsonb(OLD) - 'posted_entry_id' - 'posting_error')
       OR (OLD.posted_entry_id IS NOT NULL AND NEW.posted_entry_id IS DISTINCT FROM OLD.posted_entry_id) THEN
        RAISE EXCEPTION 'manual event facts are append-only';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER acct_manual_status_only BEFORE UPDATE OR DELETE ON acct_acctmanualentry
FOR EACH ROW EXECUTE FUNCTION acct_manual_status_only();

CREATE FUNCTION acct_validate_entry() RETURNS trigger AS $$
DECLARE balance numeric(18,4);
BEGIN
    SELECT COALESCE(SUM(debit-credit), 0) INTO balance
      FROM acct_journalline WHERE entry_id = NEW.id;
    IF balance <> 0 OR (NOT NEW.memo_only AND NOT EXISTS(SELECT 1 FROM acct_journalline WHERE entry_id = NEW.id)) THEN
        RAISE EXCEPTION 'journal entry % is empty or unbalanced by % TWD', NEW.id, balance;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;
CREATE CONSTRAINT TRIGGER acct_entry_balance AFTER INSERT ON acct_journalentry
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION acct_validate_entry();

CREATE FUNCTION acct_validate_line() RETURNS trigger AS $$
DECLARE balance numeric(18,4);
DECLARE p text;
DECLARE account_row acct_account%ROWTYPE;
BEGIN
    SELECT * INTO account_row FROM acct_account WHERE code = NEW.account_id;
    IF account_row.is_reserved THEN
        RAISE EXCEPTION 'account % is RESERVED', NEW.account_id;
    END IF;
    IF account_row.is_closing_only AND NOT EXISTS (
        SELECT 1 FROM acct_journalentry WHERE id=NEW.entry_id AND source_kind IN ('seed','opening','close')
    ) THEN
        RAISE EXCEPTION 'account % is closing-only', NEW.account_id;
    END IF;
    SELECT period INTO p FROM acct_journalentry WHERE id=NEW.entry_id;
    IF EXISTS(SELECT 1 FROM acct_journalentry WHERE id=NEW.entry_id AND memo_only) THEN
        RAISE EXCEPTION 'memo-only acknowledgement cannot carry journal lines';
    END IF;
    IF EXISTS(SELECT 1 FROM acct_period WHERE period=p AND status='CLOSED') THEN
        RAISE EXCEPTION 'acct period % is CLOSED', p;
    END IF;
    SELECT COALESCE(SUM(debit-credit), 0) INTO balance
      FROM acct_journalline WHERE entry_id = NEW.entry_id;
    IF balance <> 0 THEN
        RAISE EXCEPTION 'journal entry % unbalanced by % TWD', NEW.entry_id, balance;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;
CREATE CONSTRAINT TRIGGER acct_line_balance AFTER INSERT ON acct_journalline
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION acct_validate_line();

CREATE FUNCTION acct_check_period() RETURNS trigger AS $$
DECLARE p text;
BEGIN
    p := to_char(NEW.occurred_at AT TIME ZONE 'Asia/Taipei', 'YYYY-MM');
    IF NEW.period <> p THEN RAISE EXCEPTION 'journal period must match occurred_at'; END IF;
    IF EXISTS(SELECT 1 FROM acct_period WHERE period=p AND status='CLOSED') THEN
        RAISE EXCEPTION 'acct period % is CLOSED', p;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER acct_journal_period BEFORE INSERT ON acct_journalentry
FOR EACH ROW EXECUTE FUNCTION acct_check_period();
CREATE TRIGGER acct_manual_period BEFORE INSERT ON acct_acctmanualentry
FOR EACH ROW EXECUTE FUNCTION acct_check_period();

GRANT SELECT, INSERT ON acct_journalentry, acct_journalline, acct_acctmanualentry TO acct_writer;
GRANT SELECT ON acct_account, acct_fxrate, acct_period TO acct_writer;
GRANT SELECT ON ops_ledgerevent TO acct_writer;
REVOKE INSERT, UPDATE, DELETE ON ops_ledgerevent FROM acct_writer;
"""

DROP_CONTROLS_SQL = """
DROP TRIGGER IF EXISTS acct_manual_period ON acct_acctmanualentry;
DROP TRIGGER IF EXISTS acct_journal_period ON acct_journalentry;
DROP FUNCTION IF EXISTS acct_check_period();
DROP TRIGGER IF EXISTS acct_line_balance ON acct_journalline;
DROP FUNCTION IF EXISTS acct_validate_line();
DROP TRIGGER IF EXISTS acct_entry_balance ON acct_journalentry;
DROP FUNCTION IF EXISTS acct_validate_entry();
DROP TRIGGER IF EXISTS acct_journalline_append_only ON acct_journalline;
DROP TRIGGER IF EXISTS acct_journalentry_append_only ON acct_journalentry;
DROP FUNCTION IF EXISTS acct_append_only();
DROP TRIGGER IF EXISTS acct_manual_status_only ON acct_acctmanualentry;
DROP FUNCTION IF EXISTS acct_manual_status_only();
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [("core", "0004_dataset_settings_seed"), ("ops", "0003_alter_ledgerevent_posting_error")]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=120)),
                ('name_zh', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=20)),
                ('statement', models.CharField(max_length=20)),
                ('normal_balance', models.CharField(max_length=6)),
                ('statutory_code', models.CharField(blank=True, max_length=40)),
                ('tax_treatment', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_regime', models.CharField(blank=True, max_length=20)),
                ('subledger', models.CharField(blank=True, max_length=20)),
                ('is_reserved', models.BooleanField(default=False)),
                ('is_contra', models.BooleanField(default=False)),
                ('is_closing_only', models.BooleanField(default=False)),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('type', 'revenue'), _negated=True), ('tax_treatment__isnull', False), _connector='OR'), name='acct_revenue_has_tax_treatment')],
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('kind', models.CharField(choices=[('public', 'Public'), ('channel', 'Channel')], max_length=7)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('rate_source', models.CharField(choices=[('bot', 'Bot'), ('stated', 'Stated'), ('derived', 'Derived'), ('manual', 'Manual')], max_length=7)),
                ('evidence_ref', models.CharField(max_length=255)),
                ('source_event_key', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='acct_fx_positive'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'public'), ('rate_source__in', ['bot', 'manual'])), models.Q(('kind', 'channel'), ('rate_source__in', ['stated', 'derived'])), _connector='OR'), name='acct_fx_source_kind'), models.UniqueConstraint(fields=('rate_date', 'currency', 'kind', 'source_event_key'), name='acct_fx_source_unique')],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField()),
                ('period', models.CharField(max_length=7)),
                ('dataset_kind', models.CharField(choices=[('SAMPLE', 'Sample data — not actuals'), ('ACTUAL', 'Actual data')], max_length=6)),
                ('source_kind', models.CharField(max_length=12)),
                ('memo_only', models.BooleanField(default=False)),
                ('source_ref', models.CharField(max_length=255, unique=True)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acct.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('period', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('status', models.CharField(default='OPEN', max_length=6)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'CLOSED'])), name='acct_period_status')],
            },
        ),
        migrations.CreateModel(
            name='AcctManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('period.revalued', 'period.revalued'), ('period.accrued', 'period.accrued'), ('period.accrual_reversed', 'period.accrual_reversed'), ('tax.assessed', 'tax.assessed'), ('tax.paid', 'tax.paid'), ('owner.funds_moved', 'owner.funds_moved')], max_length=40)),
                ('occurred_at', models.DateTimeField()),
                ('period', models.CharField(max_length=7)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('payload', models.JSONField(default=dict)),
                ('basis', models.CharField(default='actual', max_length=8)),
                ('evidence_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('needs_prof_conf', models.BooleanField(default=False)),
                ('first_flagged_on', models.DateField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('posting_error', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(default='agent-2-finance-close', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acct.acctmanualentry')),
                ('fx_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acct.fxrate')),
                ('posted_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acct.journalentry')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('event_type__in', ('period.revalued', 'period.accrued', 'period.accrual_reversed', 'tax.assessed', 'tax.paid', 'owner.funds_moved'))), name='acct_manual_catalogue'), models.CheckConstraint(condition=models.Q(models.Q(('event_type__in', ['tax.assessed', 'tax.paid']), _negated=True), models.Q(('evidence_ref__isnull', False), models.Q(('evidence_ref', ''), _negated=True)), _connector='OR'), name='acct_manual_tax_evidence'), models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'owner.funds_moved'), _negated=True), ('payload__funds_type__in', ['capital', 'drawings', 'loan']), _connector='OR'), name='acct_manual_funds_type'), models.CheckConstraint(condition=models.Q(models.Q(('basis', 'estimate'), _negated=True), ('payload__has_key', 'basis_note'), _connector='OR'), name='acct_manual_estimate_basis')],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('txn_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('txn_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acct.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='acct.journalentry')),
                ('fx_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acct.fxrate')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('credit__gte', 0), ('debit__gte', 0), models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR')), name='acct_line_one_side'), models.CheckConstraint(condition=models.Q(('txn_currency__isnull', True), ('txn_currency', 'TWD'), models.Q(('txn_amount__isnull', False), ('fx_rate__isnull', False)), _connector='OR'), name='acct_line_fx_triple')],
            },
        ),
        migrations.RunSQL(CONTROLS_SQL, DROP_CONTROLS_SQL),
    ]
