# Generated by Django 6.1.1 on 2026-09-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0002_load_frozen_coa'),
    ]

    operations = [
        migrations.CreateModel(
            name='WacPosition',
            fields=[
                ('sku', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('qty_packs', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('value_twd', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('qty_packs__gte', 0), ('value_twd__gte', 0)), name='acct_wac_nonnegative')],
            },
        ),
    ]
