# Generated by Django 6.1.1 on 2026-09-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0003_wacposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
