# Generated by Django 6.1.1 on 2026-09-25 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0004_journalline_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('dataset_kind', models.CharField(choices=[('SAMPLE', 'Sample data — not actuals'), ('ACTUAL', 'Actual data')], max_length=6)),
                ('runner', models.CharField(max_length=120)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('elapsed_seconds', models.DecimalField(decimal_places=4, max_digits=12)),
                ('status', models.CharField(max_length=12)),
                ('gate_results', models.JSONField(default=list)),
                ('remaining_open', models.JSONField(default=list)),
                ('signature', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='journalline',
            name='qty_delta_packs',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='journalline',
            name='source_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ClearingCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=255)),
                ('evidence_ref', models.CharField(max_length=255)),
                ('recorded_by', models.CharField(max_length=120)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='acct.journalline')),
            ],
        ),
        migrations.CreateModel(
            name='CloseAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('action', models.CharField(max_length=12)),
                ('actor', models.CharField(max_length=120)),
                ('reason', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('close_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='acct.closerun')),
            ],
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION acct_close_record_append_only() RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION '% is append-only', TG_TABLE_NAME;
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER acct_closerun_append_only BEFORE UPDATE OR DELETE ON acct_closerun
                FOR EACH ROW EXECUTE FUNCTION acct_close_record_append_only();
                CREATE TRIGGER acct_closeaudit_append_only BEFORE UPDATE OR DELETE ON acct_closeaudit
                FOR EACH ROW EXECUTE FUNCTION acct_close_record_append_only();
            """,
            reverse_sql="""
                DROP TRIGGER acct_closeaudit_append_only ON acct_closeaudit;
                DROP TRIGGER acct_closerun_append_only ON acct_closerun;
                DROP FUNCTION acct_close_record_append_only();
            """,
        ),
    ]
