# Generated by Django 6.1.1 on 2026-09-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0005_closerun_journalline_qty_delta_packs_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='journalline',
            name='acct_line_one_side',
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', 0), ('debit__gte', 0), models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), models.Q(('credit', 0), ('debit', 0), ('source_ref__startswith', 'ops:opening-count|'), models.Q(models.Q(('account_id', '1231'), ('qty_delta_packs', 0), ('sku__isnull', False)), models.Q(('account_id', '3111'), ('qty_delta_packs__isnull', True), ('sku__isnull', False)), _connector='OR')), _connector='OR')), name='acct_line_one_side'),
        ),
    ]
