# Generated by Django 6.1.1 on 2026-09-23 14:12

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnHand',
            fields=[
                ('sku', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('qty_packs', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ops_on_hand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EtsyStatementPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('dataset_kind', models.CharField(choices=[('SAMPLE', 'Sample data — not actuals'), ('ACTUAL', 'Actual data')], max_length=6)),
                ('period', models.CharField(max_length=7, unique=True)),
                ('multiset_digest', models.CharField(max_length=64)),
                ('source_sha256', models.CharField(max_length=64)),
                ('row_count', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('dataset_kind', models.CharField(choices=[('SAMPLE', 'Sample data — not actuals'), ('ACTUAL', 'Actual data')], max_length=6)),
                ('event_type', models.CharField(choices=[('order.placed', 'order.placed'), ('order.fees_assessed', 'order.fees_assessed'), ('order.shipped', 'order.shipped'), ('order.cogs_relieved', 'order.cogs_relieved'), ('order.ship_cost_accrued', 'order.ship_cost_accrued'), ('order.ship_cost_invoiced', 'order.ship_cost_invoiced'), ('order.duty_incurred', 'order.duty_incurred'), ('order.duty_invoiced', 'order.duty_invoiced'), ('order.reprint_issued', 'order.reprint_issued'), ('order.cancelled', 'order.cancelled'), ('order.refunded', 'order.refunded'), ('payment.received', 'payment.received'), ('payment.refunded', 'payment.refunded'), ('settlement.received', 'settlement.received'), ('settlement.reversed', 'settlement.reversed'), ('po.in_transit', 'po.in_transit'), ('po.received', 'po.received'), ('po.landed_cost_adjusted', 'po.landed_cost_adjusted'), ('po.paid', 'po.paid'), ('inventory.adjusted', 'inventory.adjusted'), ('inventory.opening_counted', 'inventory.opening_counted'), ('cost.recorded', 'cost.recorded')], max_length=40)),
                ('entity_table', models.CharField(max_length=64)),
                ('entity_id', models.BigIntegerField()),
                ('occurred_at', models.DateTimeField()),
                ('amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('posted_entry_id', models.BigIntegerField(blank=True, null=True)),
                ('posting_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['posted_entry_id'], name='ops_event_unposted_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('event_type__in', ('order.placed', 'order.fees_assessed', 'order.shipped', 'order.cogs_relieved', 'order.ship_cost_accrued', 'order.ship_cost_invoiced', 'order.duty_incurred', 'order.duty_invoiced', 'order.reprint_issued', 'order.cancelled', 'order.refunded', 'payment.received', 'payment.refunded', 'settlement.received', 'settlement.reversed', 'po.in_transit', 'po.received', 'po.landed_cost_adjusted', 'po.paid', 'inventory.adjusted', 'inventory.opening_counted', 'cost.recorded'))), name='ops_event_catalogue_only'), models.CheckConstraint(condition=models.Q(('amount_minor__isnull', True), ('amount_minor__gte', 0), _connector='OR'), name='ops_event_nonnegative_amount')],
            },
        ),
        migrations.CreateModel(
            name='OpsPeriod',
            fields=[
                ('period', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('status', models.CharField(default='OPEN', max_length=6)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'CLOSED'])), name='ops_period_status')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('dataset_kind', models.CharField(choices=[('SAMPLE', 'Sample data — not actuals'), ('ACTUAL', 'Actual data')], max_length=6)),
                ('channel_order_id', models.CharField(max_length=64)),
                ('order_date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('coupon_code', models.CharField(blank=True, default='', max_length=40)),
                ('discount_funded_by', models.CharField(max_length=8)),
                ('gross_minor', models.BigIntegerField()),
                ('discount_minor', models.BigIntegerField()),
                ('buyer_paid_minor', models.BigIntegerField()),
                ('shipping_minor', models.BigIntegerField()),
                ('shipping_discount_minor', models.BigIntegerField()),
                ('tax_remitted_by_platform_minor', models.BigIntegerField(default=0)),
                ('dest_country', models.CharField(max_length=2)),
                ('status', models.CharField(default='placed', max_length=20)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('uom', models.CharField(default='PK', max_length=2)),
                ('pack_qty', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('uom', 'PK')), name='ops_product_pack_uom'), models.CheckConstraint(condition=models.Q(('pack_qty__isnull', True), ('pack_qty__gt', 0), _connector='OR'), name='ops_product_positive_pack_qty')],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('dataset_kind', models.CharField(choices=[('SAMPLE', 'Sample data — not actuals'), ('ACTUAL', 'Actual data')], max_length=6)),
                ('platform_transaction_id', models.CharField(max_length=64, unique=True)),
                ('listing_id', models.CharField(blank=True, default='', max_length=64)),
                ('line_index', models.PositiveIntegerField()),
                ('qty_packs', models.PositiveIntegerField()),
                ('unit_price_minor', models.BigIntegerField()),
                ('line_discount_minor', models.BigIntegerField()),
                ('item_total_minor', models.BigIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ops.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('dataset_kind', models.CharField(choices=[('SAMPLE', 'Sample data — not actuals'), ('ACTUAL', 'Actual data')], max_length=6)),
                ('kind', models.CharField(choices=[('opening', 'Opening'), ('received', 'Received'), ('sold', 'Sold'), ('written_off', 'Written Off'), ('returned', 'Returned'), ('adjusted', 'Adjusted')], max_length=20)),
                ('qty_delta_packs', models.IntegerField()),
                ('occurred_at', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('dataset_kind', models.CharField(choices=[('SAMPLE', 'Sample data — not actuals'), ('ACTUAL', 'Actual data')], max_length=6)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('tracking_ref', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ops.order')),
            ],
        ),
        migrations.CreateModel(
            name='EtsyStatementRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('dataset_kind', models.CharField(choices=[('SAMPLE', 'Sample data — not actuals'), ('ACTUAL', 'Actual data')], max_length=6)),
                ('row_key', models.CharField(max_length=100, unique=True)),
                ('row_type', models.CharField(max_length=40)),
                ('occurred_at', models.DateTimeField()),
                ('order_ref', models.CharField(blank=True, default='', max_length=64)),
                ('listing_ref', models.CharField(blank=True, default='', max_length=64)),
                ('currency', models.CharField(max_length=3)),
                ('amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('fee_minor', models.BigIntegerField(blank=True, null=True)),
                ('net_minor', models.BigIntegerField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.etsystatementperiod')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('amount_minor__isnull', True), ('fee_minor__isnull', False)), models.Q(('amount_minor__isnull', False), ('fee_minor__isnull', True)), _connector='OR'), name='ops_stmt_one_money_column')],
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('channel', 'channel_order_id'), name='ops_order_channel_key'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_funded_by__in', ['seller', 'platform', 'none'])), name='ops_order_funder_allowed'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_funded_by', 'none'), ('discount_minor', 0)), models.Q(('discount_funded_by__in', ['seller', 'platform']), ('discount_minor__gt', 0)), _connector='OR'), name='ops_order_funder_matches_discount'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('buyer_paid_minor__gte', 0), ('discount_minor__gte', 0), ('gross_minor__gte', 0), ('shipping_discount_minor__gte', 0), ('shipping_minor__gte', 0), ('tax_remitted_by_platform_minor__gte', 0)), name='ops_order_nonnegative_money'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('gross_minor', django.db.models.expressions.CombinedExpression(models.F('buyer_paid_minor'), '+', models.F('discount_minor')))), name='ops_order_gross_identity'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_packs__gt', 0)), name='ops_line_positive_qty'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('item_total_minor__gte', 0), ('line_discount_minor__gte', 0), ('unit_price_minor__gte', 0)), name='ops_line_nonnegative_money'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('item_total_minor', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('qty_packs'), '*', models.F('unit_price_minor')), '-', models.F('line_discount_minor')))), name='ops_line_total_identity'),
        ),
        migrations.AddConstraint(
            model_name='inventorymove',
            constraint=models.CheckConstraint(condition=models.Q(('qty_delta_packs', 0), _negated=True), name='ops_move_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='inventorymove',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['opening', 'received', 'returned']), ('qty_delta_packs__gt', 0)), models.Q(('kind__in', ['sold', 'written_off']), ('qty_delta_packs__lt', 0)), models.Q(('kind', 'adjusted'), models.Q(('qty_delta_packs', 0), _negated=True)), _connector='OR'), name='ops_move_sign_discipline'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'dispatched'), _negated=True), ('ship_date__isnull', False), _connector='OR'), name='ops_dispatched_has_ship_date'),
        ),
    ]
