# Generated by Django 6.1.1 on 2026-09-25 06:23

from django.db import migrations, models


def normalize_empty_errors(apps, schema_editor):
    apps.get_model("ops", "LedgerEvent").objects.filter(posting_error="").update(posting_error=None)


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_ops_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerevent',
            name='posting_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(normalize_empty_errors, migrations.RunPython.noop),
    ]
