# Generated by Django 6.1.1 on 2026-09-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_alter_ledgerevent_posting_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymove',
            name='value_delta_twd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddConstraint(
            model_name='inventorymove',
            constraint=models.CheckConstraint(condition=models.Q(('value_delta_twd__isnull', True), models.Q(('qty_delta_packs__gt', 0), ('value_delta_twd__gt', 0)), models.Q(('qty_delta_packs__lt', 0), ('value_delta_twd__lt', 0)), _connector='OR'), name='ops_move_value_sign'),
        ),
    ]
