# Generated by Django 6.1.1 on 2026-09-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_inventorymove_value_delta_twd_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorymove',
            name='ops_move_nonzero',
        ),
        migrations.RemoveConstraint(
            model_name='inventorymove',
            name='ops_move_sign_discipline',
        ),
        migrations.RemoveConstraint(
            model_name='inventorymove',
            name='ops_move_value_sign',
        ),
        migrations.AddConstraint(
            model_name='inventorymove',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('qty_delta_packs', 0), _negated=True), models.Q(('kind', 'opening'), ('value_delta_twd', 0)), _connector='OR'), name='ops_move_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='inventorymove',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'opening'), ('qty_delta_packs__gte', 0)), models.Q(('kind__in', ['received', 'returned']), ('qty_delta_packs__gt', 0)), models.Q(('kind__in', ['sold', 'written_off']), ('qty_delta_packs__lt', 0)), models.Q(('kind', 'adjusted'), ('qty_delta_packs__lt', 0)), _connector='OR'), name='ops_move_sign_discipline'),
        ),
        migrations.AddConstraint(
            model_name='inventorymove',
            constraint=models.CheckConstraint(condition=models.Q(('value_delta_twd__isnull', True), models.Q(('qty_delta_packs__gt', 0), ('value_delta_twd__gte', 0)), models.Q(('qty_delta_packs__lt', 0), ('value_delta_twd__lte', 0)), models.Q(('kind', 'opening'), ('qty_delta_packs', 0), ('value_delta_twd', 0)), _connector='OR'), name='ops_move_value_sign'),
        ),
    ]
