# Generated by Django 6.1.1 on 2026-09-26 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0005_remove_inventorymove_ops_move_nonzero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('dataset_kind', models.CharField(choices=[('SAMPLE', 'Sample data — not actuals'), ('ACTUAL', 'Actual data')], max_length=6)),
                ('occurred_on', models.DateField()),
                ('category', models.CharField(max_length=32)),
                ('amount_twd', models.DecimalField(decimal_places=4, max_digits=18)),
                ('settled_via', models.CharField(max_length=8)),
                ('evidence_ref', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('channel_attribution', models.CharField(blank=True, default='', max_length=16)),
                ('bank_account', models.CharField(blank=True, default='', max_length=4)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dataset_kind', 'evidence_ref'), name='ops_receipt_evidence_key'), models.CheckConstraint(condition=models.Q(('amount_twd__gt', 0)), name='ops_receipt_positive_amount')],
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('dataset_kind', models.CharField(choices=[('SAMPLE', 'Sample data — not actuals'), ('ACTUAL', 'Actual data')], max_length=6)),
                ('counted_at', models.DateField()),
                ('evidence_ref', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('opening', 'Opening'), ('adjustment', 'Adjustment')], max_length=10)),
                ('total_value_twd', models.DecimalField(decimal_places=4, max_digits=18)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dataset_kind', 'evidence_ref'), name='ops_count_evidence_key')],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('dataset_kind', models.CharField(choices=[('SAMPLE', 'Sample data — not actuals'), ('ACTUAL', 'Actual data')], max_length=6)),
                ('qty_packs', models.PositiveIntegerField()),
                ('agreed_unit_cost_twd', models.DecimalField(decimal_places=4, max_digits=18)),
                ('line_value_twd', models.DecimalField(decimal_places=4, max_digits=18)),
                ('condition', models.CharField(choices=[('sellable', 'Sellable'), ('damaged_unsellable', 'Damaged, unsellable')], max_length=20)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ops.stockcount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('count', 'product'), name='ops_count_one_line_per_sku'), models.CheckConstraint(condition=models.Q(('agreed_unit_cost_twd__gte', 0), ('line_value_twd__gte', 0)), name='ops_count_nonnegative_value')],
            },
        ),
    ]
